### ISSUE TITLE
Error starting petisco application

### ISSUE THREAD

**Issue by julian-lamoso** [alice-biometrics/petisco#132]
**Petisco version: 0.33.4**

**Starting de app with this code:**
`from petisco import Petisco

from facerest import petisco_setup

def main():
    petisco_setup()
    Petisco.get_instance().start()

if __name__ == "__main__":
    main()`

**Produces the following error:**

`petisco - INFO - Set PETISCO_LOGGING_LEVEL: INFO
petisco - INFO - {'data': {'message': {'info': {'app_name': 'face', 'app_version': '2.3.23', 'petisco_version': '0.33.4', 'environment': None}}
Traceback (most recent call last):
  File "/home/julian/miniconda3/envs/face-rest/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/julian/miniconda3/envs/face-rest/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/julian/Software/alice/face-rest/facerest/__main__.py", line 12, in <module>
    main()
  File "/home/julian/Software/alice/face-rest/facerest/__main__.py", line 8, in main
    Petisco.get_instance().start()
  File "/home/julian/miniconda3/envs/face-rest/lib/python3.6/site-packages/petisco/application/petisco.py", line 313, in start
    self._application.start()
AttributeError: 'Petisco' object has no attribute '_application'
Loading petisco from: /home/julian/Software/alice/face-rest/facerest/petisco.yml`

**Comment by fgsalomon** [comment]
I think I was the one who broke this. In the meantime you can workaround with:

```python
from petisco import Petisco

from forensics import petisco_setup

def main():
    petisco_setup()
    app = Petisco.get_instance().get_app()
    Petisco.get_instance().start()


if __name__ == "__main__":
    main()
```

**Comment by julian-lamoso** [comment]
Thanks @fgsalomon , the workaround works perfectly! What a fast support ;)
